version: 2

project_name: kubectl-waitx

builds:
  - id: kubectl_complete-waitx
    main: ./cmd/kubectl_complete-waitx
    binary: kubectl_complete-waitx
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - builds:
      - kubectl_complete-waitx
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: scripts/kubectl-waitx
        dst: kubectl-waitx

checksum:
  name_template: checksums.txt
