// Package main generates builtin condition completion data for package cmd.
package main

import (
	"cmp"
	"fmt"
	"go/constant"
	"go/format"
	"go/types"
	"log"
	"maps"
	"os"
	"path"
	"slices"
	"strings"

	"golang.org/x/tools/go/packages"
)

type conditionRef struct {
	importPath string
	constName  string
	value      string
}

func main() {
	conditionsByKind, err := loadBuiltinConditions()
	if err != nil {
		log.Fatal(err)
	}
	src, err := renderBuiltinConditions(conditionsByKind)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("builtin_conditions_gen.go", src, 0o644); err != nil {
		log.Fatal(fmt.Errorf("write builtin_conditions_gen.go: %w", err))
	}
}

func loadBuiltinConditions() (map[string][]conditionRef, error) {
	pkgs, err := packages.Load(&packages.Config{
		Mode: packages.NeedName | packages.NeedTypes,
	}, "k8s.io/api/...")
	if err != nil {
		return nil, fmt.Errorf("load packages: %w", err)
	}

	out := map[string][]conditionRef{}
	for _, pkg := range pkgs {
		if len(pkg.Errors) != 0 {
			return nil, fmt.Errorf("load %s: %s", pkg.PkgPath, pkg.Errors[0].Msg)
		}
		conditions := map[*types.TypeName][]conditionRef{}
		for _, name := range pkg.Types.Scope().Names() {
			if ref, conditionType, ok := findConditionConst(pkg.PkgPath, pkg.Types.Scope().Lookup(name)); ok {
				conditions[conditionType] = append(conditions[conditionType], ref)
			}
		}
		for _, refs := range conditions {
			slices.SortFunc(refs, func(a, b conditionRef) int {
				return cmp.Or(cmp.Compare(a.value, b.value), cmp.Compare(a.constName, b.constName))
			})
		}
		for _, name := range pkg.Types.Scope().Names() {
			strct, _ := pkg.Types.Scope().Lookup(name).Type().Underlying().(*types.Struct)
			if refs := conditions[findBuiltinConditionType(strct)]; len(refs) != 0 {
				out[name] = refs
			}
		}
	}
	return out, nil
}

func findBuiltinConditionType(resource *types.Struct) *types.TypeName {
	if resource == nil { return nil }
	var hasTypeMeta, hasObjectMeta bool
	var status *types.Struct
	for field := range resource.Fields() {
		named, _ := field.Type().(*types.Named)
		if named == nil {
			continue
		}
		if field.Embedded() {
			switch named.Obj().Name() {
			case "TypeMeta":
				hasTypeMeta = true
			case "ObjectMeta":
				hasObjectMeta = true
			}
			continue
		}
		if field.Name() == "Status" {
			status, _ = named.Underlying().(*types.Struct)
		}
	}
	if !hasTypeMeta || !hasObjectMeta || status == nil { return nil }
	for field := range status.Fields() {
		if field.Name() != "Conditions" {
			continue
		}
		slice, _ := field.Type().(*types.Slice)
		if slice == nil {
			return nil
		}
		conditionFields, _ := slice.Elem().Underlying().(*types.Struct)
		if conditionFields == nil {
			return nil
		}
		for field := range conditionFields.Fields() {
			if field.Name() == "Type" {
				conditionType, _ := field.Type().(*types.Named)
				if conditionType != nil {
					return conditionType.Obj()
				}
				return nil
			}
		}
		return nil
	}
	return nil
}

func findConditionConst(importPath string, obj types.Object) (conditionRef, *types.TypeName, bool) {
	c, ok := obj.(*types.Const)
	if !ok { return conditionRef{}, nil, false }
	named, ok := c.Type().(*types.Named)
	if !ok { return conditionRef{}, nil, false }
	basic, ok := named.Underlying().(*types.Basic)
	if !ok || basic.Kind() != types.String || !strings.HasSuffix(named.Obj().Name(), "ConditionType") { return conditionRef{}, nil, false }
	return conditionRef{
		importPath: importPath,
		constName:  c.Name(),
		value:      constant.StringVal(c.Val()),
	}, named.Obj(), true
}

func renderBuiltinConditions(conditionsByKind map[string][]conditionRef) ([]byte, error) {
	imports := map[string]bool{}
	for _, refs := range conditionsByKind {
		for _, ref := range refs {
			imports[ref.importPath] = true
		}
	}

	var src strings.Builder
	src.WriteString("// Code generated by hack/generate-builtin-conditions; DO NOT EDIT.\n")
	src.WriteString("package cmd\n\n")
	if imports := slices.Sorted(maps.Keys(imports)); len(imports) != 0 {
		src.WriteString("import (\n")
		for _, importPath := range imports {
			fmt.Fprintf(&src, "\t%s %q\n", makeImportAlias(importPath), importPath)
		}
		src.WriteString(")\n\n")
	}

	src.WriteString("var builtinConditions = map[string][]string{\n")
	for _, kind := range slices.Sorted(maps.Keys(conditionsByKind)) {
		fmt.Fprintf(&src, "\tresourceKind[*%s.%s](): toStrings(\n", makeImportAlias(conditionsByKind[kind][0].importPath), kind)
		for _, ref := range conditionsByKind[kind] {
			fmt.Fprintf(&src, "\t\t%s.%s,\n", makeImportAlias(ref.importPath), ref.constName)
		}
		src.WriteString("\t),\n")
	}
	src.WriteString("}\n")

	out, err := format.Source([]byte(src.String()))
	if err != nil {
		return nil, fmt.Errorf("format builtin conditions: %w", err)
	}
	return out, nil
}

func makeImportAlias(p string) string {
	return path.Base(path.Dir(p)) + strings.ReplaceAll(path.Base(p), ".", "")
}
