// Code generated by hack/generate-builtin-conditions; DO NOT EDIT.
package cmd

import (
	apiserverinternalv1alpha1 "k8s.io/api/apiserverinternal/v1alpha1"
	autoscalingv2beta2 "k8s.io/api/autoscaling/v2beta2"
	batchv1 "k8s.io/api/batch/v1"
	certificatesv1beta1 "k8s.io/api/certificates/v1beta1"
	corev1 "k8s.io/api/core/v1"
	extensionsv1beta1 "k8s.io/api/extensions/v1beta1"
	storagemigrationv1alpha1 "k8s.io/api/storagemigration/v1alpha1"
)

var builtinConditions = map[string][]string{
	resourceKind[*certificatesv1beta1.CertificateSigningRequest](): toStrings(
		certificatesv1beta1.CertificateApproved,
		certificatesv1beta1.CertificateDenied,
		certificatesv1beta1.CertificateFailed,
	),
	resourceKind[*extensionsv1beta1.Deployment](): toStrings(
		extensionsv1beta1.DeploymentAvailable,
		extensionsv1beta1.DeploymentProgressing,
		extensionsv1beta1.DeploymentReplicaFailure,
	),
	resourceKind[*autoscalingv2beta2.HorizontalPodAutoscaler](): toStrings(
		autoscalingv2beta2.AbleToScale,
		autoscalingv2beta2.ScalingActive,
		autoscalingv2beta2.ScalingLimited,
	),
	resourceKind[*batchv1.Job](): toStrings(
		batchv1.JobComplete,
		batchv1.JobFailed,
		batchv1.JobFailureTarget,
		batchv1.JobSuccessCriteriaMet,
		batchv1.JobSuspended,
	),
	resourceKind[*corev1.Namespace](): toStrings(
		corev1.NamespaceContentRemaining,
		corev1.NamespaceDeletionContentFailure,
		corev1.NamespaceDeletionDiscoveryFailure,
		corev1.NamespaceDeletionGVParsingFailure,
		corev1.NamespaceFinalizersRemaining,
	),
	resourceKind[*corev1.Node](): toStrings(
		corev1.NodeDiskPressure,
		corev1.NodeMemoryPressure,
		corev1.NodeNetworkUnavailable,
		corev1.NodePIDPressure,
		corev1.NodeReady,
	),
	resourceKind[*corev1.PersistentVolumeClaim](): toStrings(
		corev1.PersistentVolumeClaimControllerResizeError,
		corev1.PersistentVolumeClaimFileSystemResizePending,
		corev1.PersistentVolumeClaimVolumeModifyVolumeError,
		corev1.PersistentVolumeClaimVolumeModifyingVolume,
		corev1.PersistentVolumeClaimNodeResizeError,
		corev1.PersistentVolumeClaimResizing,
	),
	resourceKind[*corev1.Pod](): toStrings(
		corev1.ContainersReady,
		corev1.DisruptionTarget,
		corev1.PodInitialized,
		corev1.PodReadyToStartContainers,
		corev1.PodScheduled,
		corev1.PodReady,
	),
	resourceKind[*corev1.PodStatusResult](): toStrings(
		corev1.ContainersReady,
		corev1.DisruptionTarget,
		corev1.PodInitialized,
		corev1.PodReadyToStartContainers,
		corev1.PodScheduled,
		corev1.PodReady,
	),
	resourceKind[*extensionsv1beta1.ReplicaSet](): toStrings(
		extensionsv1beta1.ReplicaSetReplicaFailure,
	),
	resourceKind[*corev1.ReplicationController](): toStrings(
		corev1.ReplicationControllerReplicaFailure,
	),
	resourceKind[*apiserverinternalv1alpha1.StorageVersion](): toStrings(
		apiserverinternalv1alpha1.AllEncodingVersionsEqual,
	),
	resourceKind[*storagemigrationv1alpha1.StorageVersionMigration](): toStrings(
		storagemigrationv1alpha1.MigrationFailed,
		storagemigrationv1alpha1.MigrationRunning,
		storagemigrationv1alpha1.MigrationSucceeded,
	),
}
