apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plugin.yaml
configMapGenerator:
  - name: waitx-vars
    envs:
      - vars.env
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    config.kubernetes.io/local-config: "true"
vars:
  - name: VERSION
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: waitx-vars
    fieldref:
      fieldpath: data.VERSION
  - name: SHA_DARWIN_AMD64
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: waitx-vars
    fieldref:
      fieldpath: data.SHA_DARWIN_AMD64
  - name: SHA_DARWIN_ARM64
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: waitx-vars
    fieldref:
      fieldpath: data.SHA_DARWIN_ARM64
  - name: SHA_LINUX_AMD64
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: waitx-vars
    fieldref:
      fieldpath: data.SHA_LINUX_AMD64
  - name: SHA_LINUX_ARM64
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: waitx-vars
    fieldref:
      fieldpath: data.SHA_LINUX_ARM64
configurations:
  - varref.yaml
